#Note: I brute forced this problem which isn't a good way to solve it
ni = int(input())
if ni == 1:
    print()
    print("      *")
    print("      *")
    print("      *")
    print()
    print("      *")
    print("      *")
    print("      *")
    print()
elif ni == 2:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
elif ni == 3:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
elif ni == 4:
    print()
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print()
elif ni == 5:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
elif ni == 6:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
elif ni == 7:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print()
    print("      *")
    print("      *")
    print("      *")
    print()
elif ni == 8:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
elif ni == 9:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
elif ni == 0:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print()
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")